export const API_URLS={
    saveSentEmails:{
        endpoint:'save',
        method:'POST'
    },
    getEmailFromType:{
        endpoint:'emails',
        method:'GET'
    },
    saveDraftEmails:{
        endpoint:'save-draft',
        method:'POST'
    },
    moveEmailsToBin:{
        endpoint:'bin',
        method:'POST'
    },
    toggleStarredEmail:{
        endpoint:'starred',
        method:'POST'
    },
    deleteEmail:{
        endpoint:'delete',
        method:'DELETE'
    }
}